# Generated by Django 4.0.4 on 2022-06-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='available',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
