# Generated by Django 4.0.4 on 2022-07-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryz', '0002_products_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='desc',
            field=models.TextField(default='very gud food', max_length=100),
            preserve_default=False,
        ),
    ]
