# Generated by Django 4.0.4 on 2022-07-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryz', '0004_products_price_products_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(default='', upload_to='picture'),
            preserve_default=False,
        ),
    ]
